services:
  db:
    container_name: db-container
    image: mysql:8.0
    volumes:
      - db-volume:/var/lib/mysql
    env_file:
      - .env
    networks:
      - db-connect
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    ports:
      - "3306:3306" # MySQL을 호스트에서도 접속 가능하게 설정

  backend:
    container_name: backend-container
    build:
      context: ./backend
      cache-to:
        - type=local,dest=/tmp.buildx-cache/backend,mode=max
      cache_from:
        - type=local,src=/tmp.buildx-cache/backend
    image: wonsungjoon/backend:latest
    env_file:
      - .env
    environment:
      DATABASE_HOST: db
    networks:
      - db-connect
      - backend-connect
    depends_on:
      db:
        condition: service_healthy

  frontend:
    container_name: frontend-container
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
    image: wonsungjoon/frontend:latest
    ports:
      - "80:80"
    networks:
      - backend-connect
    depends_on:
      backend:
        condition: service_started
      db:
        condition: service_healthy

volumes:
  db-volume:

networks:
  db-connect:
  backend-connect:
